### ISSUE TITLE
persistent_get doesn't use callback?

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#2]
The current definition of persistent_get appears to completely ignore the second parameter (callback) instead simply returning the retrieved value, but the docs clearly indicate this the callback should be used to access the returned data. 

Docs out of date?

**Comment by cfry** [comment]
Right you are!
I've just updated the documentation for that
function:

<details id="persistent_get_doc_id"
style="margin-left:40px;"><summary>persistent_get</summary>
    Retreives a literal that was set with <code>persistent_set</code>
    The argument is the key to retreive. Its default value is
<code>"get_all"</code>
    which gets a JavaScript literal object that has key-value pairs for all the
    calls to <code>persistent_set</code>. If a key is not in the database,
    <code>undefined</code> will be retreived.
    <p/>
    persistent_get returns the value of the variable in the argument.<br/>
    <b>Example:</b> <br/>
    <code> persistent_set("test4", 44)</code><br/>
    <code> persistent_get("test4")</code> => 44<br/>
</details>

I'm literally in the middle of making a release.

If something goes wrong with it, your fix

will be in 1.1.5, but if not, the next release

for sure.


And thanks for the Macation. Todd counted

it as a big success, helping to improve

the Assembly guided for the next guy down the pike.

Hope to see you in San Diego sometime soon and

talk about farming!

___________
Do you happen to know:
http://www.safeharborassociates.com/
in La Jolla?
I found them via http://algae.ucsd.edu/about/index.html
As you probably know algae is the most efficient
way for biology to convert sunlight into bio-mass,
under the right conditions doubling in 24 hours.
From that we can get food (protein, carbohydrates, oils)
and from the oils we can make plastic and print it!

The guys at safe harbor have an automated way to
find the right algae for a job (there are thousands
of species)
We need special growing boxes to optimize
growing, but those boxes can largely be printed.
One of my applications for Dexter is to be able
to make such boxes. Then you do that
and use them to make your own plastic for
your other projects plus food to keep you going.

For a while, Soylent used Algae in their powder.
But they've just cut it out without explanation.
I just sent them email asking them why.
