### ISSUE TITLE
Robot.loop() iteration count not restarting on Job start

### ISSUE THREAD

**Issue by JamesWigglesworth** [cfry/dde#22]
When Robot.loop() has a first arg of a number it will work the first time the Job is run.
After the job completes and is run again without re-evaling it Robot.loop() does not run the instructions in its second arg.

**Comment by cfry** [comment]
Yes, i noticed that a couple days ago and have already fixed in. In next
release.

**Comment by JamesNewton** [comment]
Should this issue be closed? What release was it fixed in?

**Comment by JamesNewton** [comment]
Found it fixed in 2.3.15.
