### ISSUE TITLE
undefined error in call to classifier.detectMultiScale for face detection demo

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#25]
The following code, adapted from:
https://docs.opencv.org/3.4.1/js_face_detection_camera.html
and the webcam DDE example:
https://github.com/cfry/dde/blob/master/examples/opencv_process_webcam.js
Generates the following error:

> While calling the show_window handler function of: handle_webcam_video,
> undefined
> Error at dde_error (file:///C:/Program%20Files/dexter_dev_env/resources/app.asar/utils.js:29:15) at HTMLInputElement.window.submit_window (C:\Program Files\dexter_dev_env\resources\app.asar\output.js:641:9)
> 

After staring at it for rather a long time, I've found I have no clue how to debug that. I'd like to learn how to debug as much as I'd like to see this fixed. 

````
//inspired by https://davidwalsh.name/browser-camera

var cv = require("opencv.js")
let faces = new cv.RectVector();
let classifier = new cv.CascadeClassifier();

function handle_webcam_video(vals){ //vals contains name-value pairs for each
    //html elt in show_window's content with a name.
    if(vals.clicked_button_value == "init"){ 
// Clicked button value holds the name of the clicked button.
        if(navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
            navigator.mediaDevices.getUserMedia({ video: true }).then(function(stream) {
                video_id.src = window.URL.createObjectURL(stream);
                video_id.play();
            })
        }
    }
    else if (vals.clicked_button_value == "Snap Photo"){
        let context = canvas_id.getContext('2d')
        context.drawImage(video_id, 0, 0, 320, 240)
        let mat          = cv.imread(canvas_id)
        let grey_mat      = new cv.Mat(700, 700, cv.CV_8UC1)
        cv.cvtColor(mat, grey_mat, cv.COLOR_RGBA2GRAY)
        let dst      = new cv.Mat(700, 700, cv.CV_8UC1)
        cv.cvtColor(mat, dst, cv.COLOR_RGBA2GRAY)
        cv.imshow("out1_canvas_id", grey_mat)
		classifier.detectMultiScale(grey_mat, faces, 1.1, 3, 0);
        for (let i = 0; i < faces.size(); ++i) {
            let face = faces.get(i);
            let point1 = new cv.Point(face.x, face.y);
            let point2 = new cv.Point(face.x + face.width, face.y + face.height);
            cv.rectangle(dst, point1, point2, [255, 0, 0, 255]);
        }
        cv.imshow('out2_canvas_id', dst);
        mat.delete()
        mod_mat.delete()

    }
}

show_window({content:
    `<input type="button" value="init" style="margin-left:4px;"/> 
  &nbsp;webcam video display.
 <input type="button" value="Snap Photo" style="margin-left:115px;"/>
  &nbsp;from webcam video.<br/>
 <video  id="video_id"  width="320" height="240" style="border-style:solid; border-width:1; margin:3px;" autoplay></video>
 <canvas id="canvas_id" width="320" height="240" style="border-style:solid; border-width:1; margin:3px;""></canvas><br/>
  &nbsp;Photo processed to Black and White. 
</span><br/>
 <canvas id="out1_canvas_id" width="320" height="240" style="border-style:solid; border-width:1; margin:3px;""></canvas>
 <canvas id="out2_canvas_id" width="320" height="240" style="border-style:solid; border-width:1; margin:3px;""></canvas>

 `,
    title: "Processing Webcam video with DDE and OpenCV",
    width: 700, height: 600, x: 300, y:25,
    callback: handle_webcam_video})
````

**Comment by JamesNewton** [comment]
Same sort of problem with this one which is based on:
https://docs.opencv.org/3.4.1/d2/d99/tutorial_js_face_detection.html

> While calling the show_window handler function of: handle_webcam_video,
> gray_mat is not defined
> Error at dde_error (file:///C:/Program%20Files/dexter_dev_env/resources/app.asar/utils.js:29:15) at HTMLInputElement.window.submit_window (C:\Program Files\dexter_dev_env\resources\app.asar\output.js:641:9)

````
//inspired by https://davidwalsh.name/browser-camera

var cv = require("opencv.js")
let faces = new cv.RectVector();
let faceCascade = new cv.CascadeClassifier();
let msize = new cv.Size(0, 0);

faceCascade.load('haarcascade_frontalface_default.xml');

function handle_webcam_video(vals){ //vals contains name-value pairs for each
    //html elt in show_window's content with a name.
    if(vals.clicked_button_value == "init"){ // Clicked button value holds the name of the clicked button.
        if(navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
            navigator.mediaDevices.getUserMedia({ video: true }).then(function(stream) {
                video_id.src = window.URL.createObjectURL(stream);
                video_id.play();
            })
        }
    }
    else if (vals.clicked_button_value == "Snap Photo"){
        let context = canvas_id.getContext('2d')
        context.drawImage(video_id, 0, 0, 320, 240)
        let mat          = cv.imread(canvas_id)
        let grey_mat      = new cv.Mat(700, 700, cv.CV_8UC1)
        cv.cvtColor(mat, grey_mat, cv.COLOR_RGBA2GRAY)
        let dst      = new cv.Mat(700, 700, cv.CV_8UC1)
        cv.cvtColor(mat, dst, cv.COLOR_RGBA2GRAY)
        cv.imshow("out1_canvas_id", grey_mat)
		//classifier.detectMultiScale(grey_mat, faces, 1.1, 3, 0);
        faceCascade.detectMultiScale(gray_mat, faces, 1.1, 3, 0, msize, msize);

        for (let i = 0; i < faces.size(); ++i) {
            let face = faces.get(i);
            let point1 = new cv.Point(face.x, face.y);
            let point2 = new cv.Point(face.x + face.width, face.y + face.height);
            cv.rectangle(dst, point1, point2, [255, 0, 0, 255]);
        }
        cv.imshow('out2_canvas_id', dst);
        mat.delete()
        mod_mat.delete()

    }
}

show_window({content:
    `<input type="button" value="init" style="margin-left:4px;"/> 
  &nbsp;webcam video display.
 <input type="button" value="Snap Photo" style="margin-left:115px;"/>
  &nbsp;from webcam video.<br/>
 <video  id="video_id"  width="320" height="240" style="border-style:solid; border-width:1; margin:3px;" autoplay></video>
 <canvas id="canvas_id" width="320" height="240" style="border-style:solid; border-width:1; margin:3px;""></canvas><br/>
  &nbsp;Photo processed to Black and White. 
</span><br/>
 <canvas id="out1_canvas_id" width="320" height="240" style="border-style:solid; border-width:1; margin:3px;""></canvas>
 <canvas id="out2_canvas_id" width="320" height="240" style="border-style:solid; border-width:1; margin:3px;""></canvas>

 `,
    title: "Processing Webcam video with DDE and OpenCV",
    width: 700, height: 600, x: 300, y:25,
    callback: handle_webcam_video})
````

**Comment by cfry** [comment]
Type the word "debug" into the Find typein and click
the Find button.
The highlighted sections will tell you a lot about
debugging in DDE.
In particular you will see
User Guide/Debugging, a whole User Guide top level section on debugging,
and within that you'll see a link on "debugging"
which takes you to a whole DDE webinar on debugging.
Also you'll see "debugger;" a JS statement that
will "break" the code and enter the Chrome debugging
console and let you step through the code.

In your case, insert this as a new top line for the crucial function,
a la

function handle_webcam_video(vals){

   debugger;

We can get into more specifics later.

**Comment by JamesNewton** [comment]
When using the debugger, upon stepping into the classifier.detect line, the debugger shows nothing and appears to freeze. It can be closed, and operation resumes but no information of value is gleaned. 

C:/Program Files/dexter_dev_env/resources/app.asar/utils.js:29:15 is just `    var err = new Error();`

C:\Program Files\dexter_dev_env\resources\app.asar\output.js doesn't appear in the list of files under sources in the debugger, but it does open when you click on it's link in the error message under the Console. Line 641 is just the call to the dde_error() function. 

Any attempt to view the opencv.js file in the debugger, causes the debugger to lock up and need to be closed. If the debugger reopens where it left off on that file, it will immediately hang again. 

Not sure how to proceed.

**Comment by JamesNewton** [comment]
Interesting... this page gives a completely different example for how to detect faces in opencv.js
https://www.npmjs.com/package/opencv#examples
perhaps that would work better.

**Comment by cfry** [comment]
Do keep the console window open when you are stepping because
sometimes odd issues come out there.

opencv.js is large and maybe its shear size is causing problems.

Not all of OpenCV is represented in opencv.js so you
may be running into some areas that they have yet to convert.

**Comment by cfry** [comment]
I just fixed a  bug in the error printing for errors in show_window handler.
The error was in an unusual format, but in any case, I now check for that and handle it.
This probably caused you from failing to see a proper error message.

But your program still errors. It looks to me like its a low level error
inside opencv.js. I've just emailed its author with a bug report.

**Comment by cfry** [comment]
The actual error is:
While calling the show_window handler function of: handle_webcam_video,<br/>12336840 - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.

**Comment by JamesNewton** [comment]
Fixed in release 2.3.16

**Comment by kavikode** [comment]
how was this resolved because I'm still having this issue?

**Comment by JamesNewton** [comment]
Using the current latest release (not LTR) which is 3.4.4 as I write this, after File / New, going to Insert / Machine Vision / Face Recognition, then pressing Eval brings up a working demo.
