### ISSUE TITLE
Access to the file share on Dexter OS is blocked by Windows 10

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#26]
(documenting this here because I don't see it, although I know we are aware of it)

The suggestion has been made to move to an <strike>HTTP</strike> socket based file data exchange. This requires the DexRun.c program be updated to support commands for the transfer of file and directory data. E.g. a letter needs to be assigned to a command, and the block of data transferred would be a path or file name as well as a block number since data blocks are of limited size. 

Suggested operations
- Get folder item count: If the command is for a directory, and block 0, the returned data would be the number of files and folders under that dir. 

- Get folder item data: Then each would be iterated by repeating the directory and using block 1, 2, 3... for each folder/file in the dir. In that case, the return data would be the file name, size, and any other important properties.

- Get item size: To access a file, first the file path/name would be sent and then block 0 would return the size of the file in blocks

- Get item data: To get the actual file data, the block numbers 1,2,3...  are sent and each returns that block of data from the file.  On the Dexter side, it can be assumed that the file will be read out in block order, so the standard sequential fgets should be fine. Dexter just needs to track the block expected vs the block it's on (by count of calls to fgets with block size buffer) and then send back an error with the current block number if there is an issue. A lost block would, however, require reseeking... I think that can be done with lseek... might be better to close the file after each block and when reading block X, open the file, lseek to that position (block size * block number) and then gets a block. 

- Put item data: Same as before, but it's writing that block of data to the file. Because the data is now flowing from DDE to Dexter, sending the path each time wastes block space, so maybe Dexter just writes to whatever the last file that was read? So we only send the block number and the rest of the buffer is file data. Block size is buffer size less the size of the block number.

C functions (I think this works in Linux) to get info on a directory:
http://techref.massmind.org/techref/language/ccpp/cref/FUNCTIONS/directory.html

Open a file:
http://techref.massmind.org/techref/language/ccpp/cref/FUNCTIONS/fopen.html

Read data from a file:
http://techref.massmind.org/techref/language/ccpp/cref/FUNCTIONS/fgets.html

Move to a location in a file:
http://www.massmind.org/Techref/language/ccpp/cref/man/lseek.htm
(it may be fseek is right... I haven't done this is a long time)

Write data to a file:
http://www.massmind.org/techref/language/ccpp/cref/man/fputs.htm

If I can get my Dexter setup for development, and this seems good, I'll be happy to try to work on the c code.

**Comment by JamesNewton** [comment]
Per CFry:

https://nodejs.org/api/net.html#net_class_net_socket
has some documentation for you.
it LOOKS like we can just write whatever
size string we want.
See 
socket.bufferSize
and 
socket.write(data[, encoding][, callback])

encloding types are
UTF8 and hex as far as I can see in
https://nodejs.org/api/stream.html#stream_readable_setencoding_encoding

**Comment by JamesNewton** [comment]
This might be useful for debugging socket connections. e.g. before an oplet is implemented in DDE.
https://jsfiddle.net/vintharas/hbj0emek/
the default ip and port for Dexter socket communications is:
ws://192.168.1.142:50000
To attempt coms with a nonsecure (ws vs wss) port, in Chrome, you must click the shield on the far right of the address bar and allow to load the "unsafe" script.

Libwebsockets claims to do file transfers. And claims to be light. 
https://github.com/warmcat/libwebsockets
I can't seem to find any examples, but there is this:
https://libwebsockets.org/lws-api-doc-master/html/group__fops.html
I find an example of a file upload via socket at:
https://libwebsockets.org/pipermail/libwebsockets/2016-June/002598.html
Maybe someone can figure out how to implement that?

**Comment by JamesNewton** [comment]
Found out that this functionality was partly implemented in DDE already, but not in DexRun.c. 
https://github.com/HaddingtonDynamics/Dexter/wiki/write-to-robot

And stared documenting the DDE <=> Dexter communications system here:
https://github.com/HaddingtonDynamics/Dexter/wiki/DexRun-DDE-communications

At this point, it looks like DexRun.c _only_ returns the robot status, no matter what command is sent from DDE. And DDE is only able to accept status data back.

**Comment by cfry** [comment]
The instructions Dexter.read_from_robot and Dexter.write-to_robot
now allow file access without using HTTP.
