### ISSUE TITLE
speak voices all sound the same

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#30]
speak({speak_data: "Level.", voice: 0} through speak({speak_data: "Level.", voice: 3} all appear to be the same female voice.

**Comment by cfry** [comment]
On the Mac, I always get the same male voice.
I've just extended the doc to indicate this deficiency.

**Comment by cfry** [comment]
The underlying software for speech synthesis documents that the "voice"
argument changes "the person speaking".
But it doesn't. This deficiency has now been documented in the ref man
on "speak" which will be in the next release after 2.3.18
