### ISSUE TITLE
load_files vs file_content unclear

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#31]
load_files evals the file where file_content gets the file but doesn't eval it. 

The name of the function load_files doesn't indicate what the function actually does. Perhaps eval_file would be better? or load_eval_file?

**Comment by cfry** [comment]
On Wed, Aug 1, 2018 at 7:24 PM, JamesNewton <notifications@github.com>
wrote:

> load_files evals the file where file_content gets the file but doesn't
> eval it.
>
I think this is a bug report but not sure.
If so, please send me the code
and tell me what behavior you expected but what you got instead.

Is there anything about the ref man section on "load_files"
that you find unclear?

I suspect it will help our communication if you use the name
of the argument, which is "paths" (that you can see from click help)
in your comments. Distinguish between the path
of the file and the file contents as I attempted to make
clear in the doc, but perhaps I failed.
_______


> The name of the function load_files doesn't indicate what the function
> actually does. Perhaps eval_file would be better? or load_eval_file?
>
Hmm, this is an interesting point.
There's a long convention for "loading" a file but
I guess it isn't something you've come in contact with.
Let's discuss.

**Comment by JamesNewton** [comment]
So "load" implies "eval" in this case? I guess that makes sense. Loading it into the program? I can see that. Now that I think about it, that does make sense, even back to the days of cassette tape program storage and typing "LOAD" on chiclet keyboards.
