### ISSUE TITLE
read_from_robot does not work in DDE v 3.1.0 

### ISSUE THREAD

**Issue by JamesWigglesworth** [cfry/dde#38]
When starting the calibration window it tries to do a read_from_robot to get the Eye Centers.
This fails in the current version of DDE (3.1.0) and hangs up on 
"Attempting to read AdcCenters.txt from robot with IP: 192.168.1.142..."

This is done again with the same image and with DDE 2.5.13 (LTS) and it works.

**Comment by JamesNewton** [comment]
Wasn't this fixed long ago? Issue should be closed.

**Comment by cfry** [comment]
Yes, thanks for closing it.
