### ISSUE TITLE
Feature request: Save font size

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#4]
It would be wonderful to have a way to set the font size on startup.

**Comment by cfry** [comment]
How about if I persistently save the value of
fontsize (in the Editor/javascript pane)
whenever you set it.
Then relaunching DDE should restore it to
its previous value. ?

**Comment by JamesNewton** [comment]
Or a command in the in it file like the color setting? Either works.

**Comment by JamesNewton** [comment]
fixed in 1.1.18 or .19? Certainly in .19
