### ISSUE TITLE
Control.loop popup help doesn't work. 

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#48]
If you have a Control.loop or Robot.loop in the do_list, and you click on it, it does not lead to the entry in the Doc for Control.loop. 

For Robot.loop, it shows the function, for Control.loop, it shows something about an HTML attribute?

**Comment by cfry** [comment]
In DDE 3.4.7, 17 "Robot" instructions were deprecated and replaced with same_named "Control" instructions. Example: <code>Robot.loop</code> is now  <code>Control.loop</code>. The deprecated instructions are:  
<ul><li><code>Robot.break</code></li>
<li><code>Robot.go_to</code></li>
<li><code>Robot.loop</code></li>
<li><code>Robot.label</code></li>
<li><code>Robot.suspend</code></li>
<li><code>Robot.unsuspend</code></li>
<li><code>Robot.sync_point</code></li>
<li><code>Robot.wait_until</code></li>
<li><code>Robot.include_job</code></li>
<li><code>Robot.send_to_job</code></li>
<li><code>Robot.sent_from_job</code></li>
<li><code>Robot.start_job</code></li>
<li><code>Robot.stop_job</code></li>
<li><code>Robot.debugger</code></li>
<li><code>Robot.step_instructions</code></li>
<li><code>Robot.error</code></li>
<li><code>Robot.f_any_errors</code></li></ul> After DDE 3.6.0, click help for each of those deprecated instructions telling you that they are deprecated, and directing you to their replacements.

### Control.loop
Also click help for Control.loop has been fixed after DDE 3.6.0
