### ISSUE TITLE
speek in out.js provides different parameters to callback depending on platform

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#56]
On the Job Engine, the callback is called by "exec" and has error, stdout, and stderror paramters, on the PC it's called by the built in speech synth, and provides an "event" object. 

Combining those seems impossible. You suggested providing two different callbacks.

**Comment by cfry** [comment]
I've extended speak to take a 2nd arg "node_callback".
When running on the job engine, it will use the node_callback
instead of the "callback" callback.
I've documented ref man speak to tell about this new argument.
It takes different args than the dde "callback".
