### ISSUE TITLE
Drop Down for Search Results not Dropping Down

### ISSUE THREAD

**Issue by CantFindABatterman** [cfry/dde#71]
![image](https://user-images.githubusercontent.com/88004125/127054246-271a799a-f839-4ab2-9c1d-4a03c3d1da2d.png)

**Comment by JamesNewton** [comment]
The twist downs are in the upper right corner. The example on in the output panel at the bottom is just a picture to show you want to look for in the upper right.

**Comment by cfry** [comment]
James N comment above is correct.
But, the twistdown + Orange Rows in the output pane was admittedly ambiguous. 
It has been extended with 
"(in the Doc pane)" to make it clearer where the orange rows to be twisted down are.
Thanks to CantFindABatterman for helping make this clearer.
