### ISSUE TITLE
Simulator doesn't support physics

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#88]
It would be so nice to be able to pick up simulated objects, and run into things and feel it, and so on.

**Comment by cfry** [comment]
The physics engine that I currently think is best is:
http://www.goblinphysics.com/examples/constraint-point.html
the buy lives in Colorado so hopefully we could get some help from him if need be.
This may need an update to Three.js version number which I believe has an incompatibility
with our the version of Threejs we now use with: BoxGeometry.
I don't think its too hard to update the current code which would be  good idea
to do anyway.

**Comment by JamesNewton** [comment]
Added in DDE4.2.2 by @lmarsbrown and @cfry
