### ISSUE TITLE
Clicking on the link to the youtube video loses you work.

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#9]
1. Write code for 30 minutes without saving.
2. Click the link for "Video tutorial of DDE" under Users Guide, User Interface
3. Try for 10 more minutes to find a way to get back into DDE and save your code.

Workaround: NEVER fail to save your code constantly. Duh.

Suggested fix: Open links in a new browser window.

**Comment by cfry** [comment]
Good Suggestion. DONE! Now clicking DDE Video link opens in a new browser window.

I usually keep the "Save on Eval" checkbox (in the Output pane header) checked.
I usually click the Eval button more than once a minute when coding.
This auto saves the file every time I Eval. 
But the real reason I Eval so often is, its easiest to catch bugs
when you know its something you JUST did.
